

services:
  nginx:
    build: ./docker/nginx
    ports:
      - "8080:80"
    depends_on:
      - node-service

  node-service:
    build: ./docker/api
    environment:
      DB_HOST: db
      DB_USERNAME: root
      DB_PASSWORD: rootpassword
      DB_DATABASE: books
    depends_on:
      - db

  db:
    build: ./docker/db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: books
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
